module "incident_auto_triage_workflow" {
  source = "github.com/port-experimental/terraform-port-workflow?ref=1.0.1"

  identifier                = "tf-incident-auto-triage"
  title                     = "Incident Auto-Triage Generated by Terraform"
  icon                      = "Alert"
  description               = "Terraform Example: Pick an incident, have AI investigate it with Port and Notion context, then post a triage summary to Slack."
  category                  = var.category
  allow_anyone_to_view_runs = true
  nodes                     = local.incident_auto_triage.nodes
  connections               = local.incident_auto_triage.connections
}
